# Generated by Django 3.1a1 on 2020-08-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_merge_20200723_1541'),
        ('payment', '0007_payment_is_refill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='company',
        ),
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='main.company', verbose_name='Підписка на компанію'),
        ),
    ]
