# Generated by Django 3.1a1 on 2020-09-07 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20200907_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час закриття платежу'),
        ),
        migrations.AddField(
            model_name='payment',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час відкриття платежу'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billed_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billed_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата кінця'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'OK'), (2, 'Закінчилась'), (3, 'Пробний період'), (4, 'Безкоштовна'), (5, 'Очікування продовження'), (6, 'Не комерційна'), (7, 'В процесі оплати')], default=7, verbose_name='Статус підписки'),
        ),
    ]
