# Generated by Django 3.1a1 on 2020-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20200911_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'OK'), (2, 'Закінчилась'), (3, 'Пробний період'), (4, 'Очікування продовження'), (5, 'Не комерційна'), (6, 'В процесі оплати'), (7, 'Не активна')], default=6, verbose_name='Статус підписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.SmallIntegerField(choices=[(1, 'Безкоштовний'), (2, 'Бізнес'), (3, 'Бізнес +'), (4, 'Некомерційний')], default=1, unique=True, verbose_name='Аліас(код) плану'),
        ),
    ]
