# Generated by Django 3.1a1 on 2020-07-22 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0126_auto_20200722_1753'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payment.subscriptionplan', verbose_name='План підписки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ManyToManyField(related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Платник'),
        ),
        migrations.AlterField(
            model_name='priceperperiod',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_periods', to='payment.subscriptionplan', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.ManyToManyField(related_name='subscriptions', to='main.Company', verbose_name='Підписка на компанію'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='payment.subscriptionplan', verbose_name='План підписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(related_name='plan_features', to='payment.SubscriptionPlanFeature', verbose_name='Можливості тарифного плану'),
        ),
    ]
