# Generated by Django 3.1a1 on 2020-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200722_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='pay_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Позначено як видалене'),
        ),
        migrations.AlterField(
            model_name='priceperperiod',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Позначено як видалене'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Позначено як видалене'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Позначено як видалене'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanfeature',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Позначено як видалене'),
        ),
    ]
