# Generated by Django 3.1a1 on 2020-07-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200723_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='non_commercial',
            field=models.BooleanField(default=False, verbose_name='Не комерційний тариф'),
        ),
        migrations.AddField(
            model_name='subscriptionplanfeature',
            name='tip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підказка'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payment.subscriptionplan', verbose_name='План підписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Аліас(код) плану'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanfeature',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва можливості'),
        ),
    ]
