# Generated by Django 3.1a1 on 2020-08-01 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_auto_20200723_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Платник'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Промоперіод'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'OK'), (2, 'Закінчилась'), (3, 'Безкоштовна'), (4, 'Пробний період'), (5, 'Очікування продовження'), (6, 'Не комерційна')], default=3, verbose_name='Статус підписки'),
        ),
    ]
