# Generated by Django 3.1a1 on 2020-08-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Час змінення')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Позначено як видалене')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Час видалення')),
                ('name', models.CharField(max_length=100, verbose_name='Назва періоду')),
            ],
            options={
                'verbose_name': 'Період',
                'verbose_name_plural': 'Періоди',
            },
        ),
        migrations.AlterModelOptions(
            name='priceperperiod',
            options={'ordering': ['price'], 'verbose_name': 'Ціна за період підписки', 'verbose_name_plural': 'Ціна за період підписки'},
        ),
        migrations.AlterField(
            model_name='priceperperiod',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_periods', to='payment.subscriptionplan', verbose_name='Тариф'),
        ),
    ]
