# Generated by Django 3.1a1 on 2020-08-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200803_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingPeriod',
        ),
    ]
