# Generated by Django 3.1a1 on 2020-09-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0011_delete_billingperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceperperiod',
            options={'ordering': ['price'], 'verbose_name': 'Ціна за період підписки', 'verbose_name_plural': 'Ціни за період підписки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplanfeature',
            options={'verbose_name': 'Можливість тарифного плану', 'verbose_name_plural': 'Можливості тарифного плану'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='company',
        ),
        migrations.AddField(
            model_name='subscription',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'OK'), (2, 'Закінчилась'), (3, 'Пробний період'), (4, 'Безкоштовна'), (5, 'Очікування продовження'), (6, 'Не комерційна')], default=3, verbose_name='Статус підписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.SmallIntegerField(choices=[(1, 'Безкоштовний'), (2, 'Бізнес'), (3, 'Бізнес +'), (4, 'Некомерційний')], default=1, verbose_name='Аліас(код) плану'),
        ),
    ]
