# Generated by Django 3.1a1 on 2020-09-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20200907_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_per_period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.priceperperiod', verbose_name='Ціна за період'),
            preserve_default=False,
        ),
    ]
