# Generated by Django 3.1a1 on 2020-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20200907_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Успішний'), (2, 'Провал'), (3, 'Очікування'), (4, 'Перевірка')], default=3, verbose_name='Статус платежу'),
        ),
    ]
