# Generated by Django 3.1a1 on 2020-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_payment_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_refill',
            new_name='is_deposit',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сума платежу'),
        ),
    ]
