# Generated by Django 3.1a1 on 2020-09-09 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20200909_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10, 'Сума поповнення має бути 10 грн або більше')], verbose_name='Сума платежу'),
        ),
    ]
