# Generated by Django 3.1a1 on 2020-09-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20200910_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price_per_period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.priceperperiod', verbose_name='Ціна за період'),
        ),
    ]
