# Generated by Django 3.1a1 on 2020-09-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20200911_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'OK'), (2, 'Закінчилась'), (3, 'Пробний період'), (4, 'Очікування продовження'), (5, 'Не комерційна'), (6, 'В процесі оплати')], default=6, verbose_name='Статус підписки'),
        ),
    ]
