# Generated by Django 2.2.8 on 2020-04-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySearchReplica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
