# Generated by Django 2.2.8 on 2020-04-27 01:16

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
