# Generated by Django 2.2.8 on 2020-04-27 06:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0002_auto_20200427_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysearchreplica',
            name='content_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='name_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='companysearchreplica',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_vector', 'content_vector'], name='search_repl_name_ve_7beb49_gin'),
        ),
    ]
