# Generated by Django 2.2.8 on 2020-04-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0003_auto_20200427_0648'),
    ]

    migration = '''
            CREATE TRIGGER name_search_update BEFORE INSERT OR UPDATE
            ON search_replicas_companysearchreplica FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(name_vector, 'pg_catalog.english', name);

            UPDATE search_replicas_companysearchreplica set ID = ID;
        '''

    reverse_migration = '''
            DROP TRIGGER name_search_update ON search_replicas_companysearchreplica;
    '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
