# Generated by Django 2.2.8 on 2020-05-09 22:38

import django.contrib.postgres.search
from django.db import migrations, models
import main.utils
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0005_create_vector_search_trigger_on_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysearchreplica',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='hits_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to=main.utils.path_and_rename),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='ppoi_image',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='raw_rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='stars_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companysearchreplica',
            name='content',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='companysearchreplica',
            name='content_vector',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysearchreplica',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='companysearchreplica',
            name='name_vector',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, null=True),
        ),
    ]
