# Generated by Django 2.2.8 on 2020-05-09 22:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0006_auto_20200509_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysearchreplica',
            name='categories_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysearchreplica',
            name='tags_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
