# Generated by Django 2.2.8 on 2020-05-09 22:47

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0007_auto_20200509_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysearchreplica',
            name='content_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='companysearchreplica',
            name='name_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
