# Generated by Django 2.2.8 on 2020-05-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0008_auto_20200509_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysearchreplica',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
