# Generated by Django 3.1a1 on 2020-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_replicas', '0009_auto_20200509_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysearchreplica',
            name='slug',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
